Only deploy master branch

diff --git a/bin/pymdeploy b/bin/pymdeploy
--- a/bin/pymdeploy
+++ b/bin/pymdeploy
@@ -78,6 +78,12 @@ parse_args() {
 parse_args $ARGS
 
 do_check_git_repo() {
+    CURRENT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
+    if [ "$CURRENT_BRANCH" != "master" ]; then
+        echo "ERROR: The current branch is not master - Cannot deploy!"
+        exit 1
+    fi
+
     IS_DIRTY_CLONE=$(git status --short --porcelain | wc -l)
     if [ "$IS_DIRTY_CLONE" -gt 0 ]; then
         echo "ERROR: $PWD is not clean! Commit and re-run."
